Customers/feature/register turn
mauriciobergallo/fernorte-app-2w2 pull request #38
Opened 2023-10-21 23:38 UTC by 114184-SUPPO-IMANOL

2023-10-25 15:49 UTC, mauriciobergallo requested changes
- No se puede actualizar angular.json

2023-10-27 22:15 UTC, 113493-Grecco-Daniel approved these changes
ok change angular.json

2023-10-28 16:27 UTC, mauriciobergallo requested changes
Hay que descartar los cambios del archivo angular.json, no volver a modificarlo

2023-10-31 19:21 UTC, mauriciobergallo requested changes

2023-10-31 19:21 UTC, mauriciobergallo commented on src/app/modules/customer/components/btn-customer/btn-customer.component.html
> +        <!-- <h2>Soy Cliente Registrado</h2> -->
Si no se usa, borrar, no comentar

2023-10-31 19:21 UTC, mauriciobergallo commented on src/app/modules/customer/components/btn-customer/btn-customer.component.html
> +             <!--<label for="document">Document Number:</label>
Si no se usa, borrar, no comentar

2023-10-31 19:21 UTC, mauriciobergallo commented on src/app/modules/customer/components/create-customer/create-customer.component.ts
> +//	@ViewChild('customerForm') customerForm!: NgForm;
Si no se usa, borrar, no comentar

2023-10-31 19:21 UTC, mauriciobergallo commented on src/app/modules/customer/components/employee-registration/employee-registration.component.ts
> +	//@ViewChild('employeeForm') employeeForm!: NgForm;
Si no se usa, borrar, no comentar

2023-10-31 19:21 UTC, mauriciobergallo commented on src/app/modules/customer/components/login/login.component.html
> +    <!-- <div class="form-check text-start my-3">
Si no se usa, borrar, no comentar

2023-10-31 19:21 UTC, mauriciobergallo commented on src/app/modules/customer/models/employee.ts
> +export interface Employee {
Mapear las entidades... no usar pascal case... usar camelCase

2023-10-31 19:21 UTC, mauriciobergallo commented on src/app/modules/customer/models/employeeResponseDTO.ts
> +    id_employee: number,
mismo que antes... usar camelCase

2023-10-31 19:21 UTC, mauriciobergallo commented on src/app/modules/customer/models/turn-response.ts
> +  number: number;
camel case

2023-11-05 14:09 UTC, closed without merging