Sales&bill/develop
mauriciobergallo/fernorte-app-2w2 pull request #41
Opened 2023-10-22 16:14 UTC by 113833-PRADO

2023-10-25 15:50 UTC, mauriciobergallo requested changes
- No se puede actualizar angular.json
- No se puede actualizar app.component.ts

2023-10-28 16:27 UTC, mauriciobergallo requested changes
El archivo angular.json no se debe tocar

2023-10-31 23:53 UTC, mauriciobergallo approved these changes
Cambiar lo solicitado, acomodar el inglés español... o una cosa u otra... no un mix

2023-10-31 23:53 UTC, mauriciobergallo commented on src/app/modules/sales/models/SaleOrderModel.ts
> +    id_sale_order?: number = 0;
usar camel case...

2023-10-31 23:53 UTC, mauriciobergallo commented on src/app/modules/sales/services/salesOrder/sale-order-service.service.ts
> +  // getSaleOrdersByFilter(filter: string): SaleOrderModel[] {
Si no sirve, eliminar el código no comentar

2023-10-31 23:53 UTC, mauriciobergallo commented on src/app/modules/sales/services/salesOrder/sale-order-service.service.ts
> +      id_sale_order: id,
Camel case

2023-11-07 18:20 UTC, mauriciobergallo requested changes
los assets no están permitidos en el src, deberían estar dentro de su propio módulo

2023-11-11 22:54 UTC, mauriciobergallo requested changes
Por que aparecen moficiados el README, package-lock.json y package.json? lo mismo apsa con app.module.ts, assets ... etc? 
Lo único que tienen que modificar es dentro de su carpeta, por favor corregir antes de seguir agregando commits.

2023-11-12 14:28 UTC, 113833-PRADO commented
Buen dia Pprofesor, se modificaron esos archivos realizando el pull para traer las librerias que instalo, con respecto a los asset le agradeceriamos si puede indicarnos como resolverlos

2023-11-12 20:40 UTC, 113833-PRADO commented
@mauriciobergallo Eliminamos el archivo de asset que no debia estar y segun comprendemos los archivos README, package-lock.json y package.json estan iguales que los de release. Nos encontramos a la espera de su respuesta para confirmar que asi sea.

2023-11-14 09:24 UTC, mauriciobergallo approved these changes
Ahora si.

2023-11-14 15:35 UTC, merged